# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Byte of cookie
tagline:          'Work It Harder Make It Better Do It Faster, Makes Us Stronger'
description:      'lessons learned during front-end and back-end programming'
url:              http://pgrzego.github.io
baseurl:          /

author:
  photo:          https://gravatar.com/avatar/85bde35e8fc328484a646e60df56c5ea.jpg
  url:            https://twitter.com/mdo

paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: \n\n


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
